<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Items\Katana\Metal\CopperKatana.png" />
	  <None Remove="Items\Katana\Metal\GoldKatana.png" />
	  <None Remove="Items\Katana\Metal\LeadKatana.png" />
	  <None Remove="Items\Katana\Metal\PlatinumKatana.png" />
	  <None Remove="Items\Katana\Metal\SilverKatana.png" />
	  <None Remove="Items\Katana\Metal\TinKatana.png" />
	  <None Remove="Items\Katana\Metal\TungstenKatana.png" />
	</ItemGroup>

	<!-- References -->
	<ItemGroup>
	<Reference Include="StructureHelper">
	    <HintPath>..\ModAssemblies\StructureHelper.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>